# -*- mode: makefile -*-

OBJ_FILES = fzero.o test_vmec_to_gs2_geometry_interface.o vmec_to_gs2_geometry_interface.o

# Dependencies:
fzero.o:
test_vmec_to_gs2_geometry_interface.o: vmec_to_gs2_geometry_interface.o 
vmec_to_gs2_geometry_interface.o: mini_libstell/mini_libstell.a
