# Compiler: GNU g95/gcc

FC = g95
CC = gcc
F90FLAGS += -ffree-line-length-huge -fno-backslash
CPPFLAGS += -DFCOMPILER=_G95_

ifdef DBLE
	F90FLAGS += -r8
endif

ifdef STATIC
	LDFLAGS += -static
endif

ifdef DEBUG
	F90FLAGS += -g -Wall -fimplicit-none -fbounds-check -ftrace=full
	F90OPTFLAGS =
	CFLAGS += -g -Wall -fbounds-check
	COPTFLAGS =
else
	ifdef OPT
		F90OPTFLAGS += -O3
		COPTFLAGS += -O3
	endif

	ifeq ($(findstring gprof,$(PROF)),gprof)
		F90FLAGS += -pg
		CFLAGS += -pg
	endif
endif
