# Compiler: Fujitsu f90
# currently not supported

FC = 
F90FLAGS = -A m -C cdRR8 -X9 -static-flib -Kfast

ifndef USE_NR_RAN
$(warning USE_NR_RAN cannot be off for Fujitsu Compiler)
	override USE_NR_RAN = on
endif

ifdef STATIC
	F90FLAGS +=
endif

ifdef DEBUG
	F90FLAGS += -g -H easu
	F90OPTFLAGS =
else
	F90OPTFLAGS += -O -f 2004,2006,2008 -Wa,--no-warn
endif
