        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_GET_DEFAULT_ADVANCED_PARAMETERS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_GET_DEFAULT_ADVANCED_PARAMETERS(        &
     &ADVANCED_PARAMETERS_OUT)
              USE GEOMETRY
              TYPE (ADVANCED_PARAMETERS_TYPE), INTENT(OUT) ::           &
     &ADVANCED_PARAMETERS_OUT
            END SUBROUTINE GEOMETRY_GET_DEFAULT_ADVANCED_PARAMETERS
          END INTERFACE 
        END MODULE GEOMETRY_GET_DEFAULT_ADVANCED_PARAMETERS__genmod
