        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_SET_INPUTS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_SET_INPUTS(EQUILIBRIUM_TYPE,EQFILE_IN,  &
     &IRHO_IN,RHOC_IN,BISHOP_IN,NPERIOD_IN,NTHETA)
              INTEGER(KIND=4), INTENT(IN) :: EQUILIBRIUM_TYPE
              CHARACTER(LEN=800), INTENT(IN) :: EQFILE_IN
              INTEGER(KIND=4), INTENT(IN) :: IRHO_IN
              REAL(KIND=8), INTENT(IN) :: RHOC_IN
              INTEGER(KIND=4), INTENT(IN) :: BISHOP_IN
              INTEGER(KIND=4), INTENT(IN) :: NPERIOD_IN
              INTEGER(KIND=4), INTENT(INOUT) :: NTHETA
            END SUBROUTINE GEOMETRY_SET_INPUTS
          END INTERFACE 
        END MODULE GEOMETRY_SET_INPUTS__genmod
