        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_GET_MILLER_PARAMETERS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_GET_MILLER_PARAMETERS(                  &
     &MILLER_PARAMETERS_OUT)
              USE GEOMETRY
              TYPE (MILLER_PARAMETERS_TYPE), INTENT(OUT) ::             &
     &MILLER_PARAMETERS_OUT
            END SUBROUTINE GEOMETRY_GET_MILLER_PARAMETERS
          END INTERFACE 
        END MODULE GEOMETRY_GET_MILLER_PARAMETERS__genmod
