        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_GET_COEFFICIENTS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_GET_COEFFICIENTS(GRID_SIZE,             &
     &COEFFICIENTS_OUT)
              USE GEOMETRY
              INTEGER(KIND=4), INTENT(IN) :: GRID_SIZE
              TYPE (COEFFICIENTS_TYPE) :: COEFFICIENTS_OUT(GRID_SIZE)
            END SUBROUTINE GEOMETRY_GET_COEFFICIENTS
          END INTERFACE 
        END MODULE GEOMETRY_GET_COEFFICIENTS__genmod
