        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_SET_ADVANCED_PARAMETERS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_SET_ADVANCED_PARAMETERS(                &
     &ADVANCED_PARAMETERS_IN)
              USE GEOMETRY
              TYPE (ADVANCED_PARAMETERS_TYPE), INTENT(IN) ::            &
     &ADVANCED_PARAMETERS_IN
            END SUBROUTINE GEOMETRY_SET_ADVANCED_PARAMETERS
          END INTERFACE 
        END MODULE GEOMETRY_SET_ADVANCED_PARAMETERS__genmod
