        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_VARY_S_ALPHA__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_VARY_S_ALPHA(S_HAT_INPUT_IN,            &
     &BETA_PRIME_INPUT_IN)
              REAL(KIND=8), INTENT(IN) :: S_HAT_INPUT_IN
              REAL(KIND=8), INTENT(IN) :: BETA_PRIME_INPUT_IN
            END SUBROUTINE GEOMETRY_VARY_S_ALPHA
          END INTERFACE 
        END MODULE GEOMETRY_VARY_S_ALPHA__genmod
