        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_GET_CONSTANT_COEFFICIENTS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_GET_CONSTANT_COEFFICIENTS(              &
     &CONSTANT_COEFFICIENTS_OUT)
              USE GEOMETRY
              TYPE (CONSTANT_COEFFICIENTS_TYPE), INTENT(OUT) ::         &
     &CONSTANT_COEFFICIENTS_OUT
            END SUBROUTINE GEOMETRY_GET_CONSTANT_COEFFICIENTS
          END INTERFACE 
        END MODULE GEOMETRY_GET_CONSTANT_COEFFICIENTS__genmod
