        !COMPILER-GENERATED INTERFACE MODULE: Sun Nov  3 19:30:30 2013
        MODULE GEOMETRY_CALCULATE_COEFFICIENTS__genmod
          INTERFACE 
            SUBROUTINE GEOMETRY_CALCULATE_COEFFICIENTS(GRID_SIZE)
              INTEGER(KIND=4), INTENT(OUT) :: GRID_SIZE
            END SUBROUTINE GEOMETRY_CALCULATE_COEFFICIENTS
          END INTERFACE 
        END MODULE GEOMETRY_CALCULATE_COEFFICIENTS__genmod
