# Host: ARCHER2 (HPE Cray EX)
# Requires cray-fftw, cray-hdf5, cray-netcdf, and cray-libsci modules to be loaded

helplocal:
		# GK_SYSTEM = archer2
		# You are using Makefile.archer2 to build stella executables on ARCHER2.

define STANDARD_SYSTEM_CONFIGURATION
module restore PrgEnv-gnu ;\
module load cray-fftw ;\
module load cray-hdf5 ;\
module load cray-libsci ;\
module load cray-netcdf ;\
echo Module configuration complete;\
export MAKEFLAGS='-j -I Makefiles';
endef

PRGENV_CRAY=$(shell if module is-loaded cpe-cray; then echo true; else echo false; fi;)
ifeq ($(PRGENV_CRAY),true)
      COMPILER=cray
else
      COMPILER=gnu-gfortran
endif

CRAY_SYSTEM=true

# Switch on netcdf
ifdef NETCDF_DIR
	USE_NETCDF = on
else
	ifdef CRAY_NETCDF_DIR
		CRAY_NETCDF = on
		USE_NETCDF = on
	else
		override USE_NETCDF =
	endif
endif

ifdef PGPLOT_DIR
	PGPLOT_LIB = -lpgplot -L$$PGPLOT_DIR
endif

# Include compiler flags (which might try to set LAPACK_LIB = -llapack)
include $(COMPILATION_DIR)/Makefiles/Compilers/Makefile.$(COMPILER)

# Use Cray wrappers
FC=ftn
CC=cc
MPIFC=ftn
MPICC=cc

H5CC_par = cc
H5FC_par = ftn
HFCC = cc
H5FC = ftn

ifeq ($(USE_FFT),fftw)
	FFT_INC = 
	ifdef DBLE
		FFT_LIB = -ldfftw -ldrfftw
	else
		FFT_LIB = -lsfftw -lsrfftw
	endif
endif
ifeq ($(USE_FFT),fftw3)	
        CPPFLAGS   += -I $$FFTW_INC
endif	

# Cray wrappers (ftn) link Cray-LibSci automatically.
# 'override' ensures this variable stays empty even if included sub-makefiles attempt to set it.
override LAPACK_LIB = 

ifdef USE_NETCDF
  ifdef OWN_NETCDF
	NETCDF_INC = -I $(NETCDF_DIR)/include/
	NETCDF_LIB = -L $(NETCDF_DIR)/lib -lnetcdf
  endif
endif
