name: Documentation
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt update &&
           sudo apt install -y
                 make
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdff-dev
                 rsync

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install FORD
      run: |
        python -m pip install --upgrade pip
        pip install ford
        ford --version
        
    - name: Build documentation
      run: |
        export GK_SYSTEM=gnu_ubuntu
        git submodule update --init --recursive
        make -I Makefiles doc
        
    - name: Checkout pages branch
      run: |
        git checkout -b gh-pages --track origin/gh-pages
        
    - name: Move built documentation
      run: |
        cp -vr DOCUMENTATION/automatic_documentation_manual_pages/* .
        rm -rf DOCUMENTATION/automatic_documentation_manual_pages
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add built documentation
        add_options: '--all'
