name: Documenation
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Install dependencies
      run: sudo apt update &&
           sudo apt install -y
                 make
                 libfftw3-dev
                 libnetcdf-dev
                 libnetcdff-dev
                 python3
                 python3-pip
                 rsync

    - name: Install FORD
      run: |
        pip3 install --upgrade pip
        pip3 install ford
        ford --version
    - name: Build documentation
      run: |
        export GK_SYSTEM=gnu_ubuntu
        make -I Makefiles doc
    - name: Checkout pages branch
      run: |
        git checkout -b gh-pages --track origin/gh-pages
    - name: Move built documentation
      run: |
        cp -vr docs/html/* .
        rm -rf docs/html
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add built documentation
        add_options: '--all'
