name: Tests
on: push

defaults:
  run:
    shell: bash

jobs:
  fprettify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Fix formatting with fprettify
      run: |
        pip install fprettify
        fprettify --version
        fprettify --config-file .fprettify.conf $(git ls-files | grep -E "\.f[p9][p0]")
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci] Apply fprettify changes"
        
